/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 24.11
 * Usage: Interface to C
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#include "HCHalcon_UI.h"

extern HUserImport int HHalcon_UIGetOffset();

int offset = -1;

Herror HcPreCallUser(int proc_index_local, Hproc_handle *proc_handle)
{
  if (offset < 0)
  {
    /* First use of this extension package, query my offset */
    if (0 > (offset = HHalcon_UIGetOffset()))
    {
      /*
       * Either the HALCON library was not initialized or the extension package
       * was not loaded. Make sure HALCON is initialized and check the offset
       * again.
       */
      Herror err = HcPreCall(-1, proc_handle);
      if (H_MSG_OK != err)
        return err;
      if (0 > (offset = HHalcon_UIGetOffset()))
      {
        /* The extension package could not be loaded. */
        return H_ERR_UEXTNI;
      }
      HcPostCall(*proc_handle, H_MSG_OK);
      *proc_handle = NULL;
    }
  }
  return HcPreCall(offset + proc_index_local, proc_handle);
}

HUserExport Herror T_WCloseWebServer(const Htuple server_id)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(0,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&server_id);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_WSendWebData(const Htuple server_id, const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(1,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&server_id);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_WRecvWebData(const Htuple server_id, const Htuple timeout, const Htuple DictHandle)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(2,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&server_id);
  if (err == H_MSG_OK) err = HcStoreICT(ph,1,&timeout);
  if (err == H_MSG_OK) err = HcStoreICT(ph,2,&DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror T_WCreateWebServer(const Htuple port, const Htuple web_root, Htuple *server_id)
{
  Hproc_handle ph;
  Herror err = H_MSG_OK;

  err = HcPreCallUser(3,&ph);
  if (err == H_MSG_OK) err = HcStoreICT(ph,0,&port);
  if (err == H_MSG_OK) err = HcStoreICTEnc(ph,1,&web_root);
  if (err == H_MSG_OK)
  {
    HcInitOCT(ph,0,server_id);
    err = HcCall(ph);
  }
  err = HcStoreOCT(ph,0,server_id,err);
  return HcPostCall(ph,err);
}

HUserExport Herror WCloseWebServer(Hlong server_id)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(0,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,server_id);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror WSendWebData(Hlong server_id, Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(1,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,server_id);
  if (err == H_MSG_OK) HcStoreICL(ph,1,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror WRecvWebData(Hlong server_id, Hlong timeout, Hlong DictHandle)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(2,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,server_id);
  if (err == H_MSG_OK) HcStoreICL(ph,1,timeout);
  if (err == H_MSG_OK) HcStoreICL(ph,2,DictHandle);
  if (err == H_MSG_OK)
  {
    err = HcCall(ph);
  }
  return HcPostCall(ph,err);
}

HUserExport Herror WCreateWebServer(Hlong port, const char *web_root, Hlong *server_id)
{
  Hproc_handle ph;
  Herror err;
  err = HcPreCallUser(3,&ph);
  if (err == H_MSG_OK) HcStoreICL(ph,0,port);
  if (err == H_MSG_OK) HcStoreICSEnc(ph,1,web_root);
  if (err == H_MSG_OK)
  {
    HcInitOCL(ph,0);
    err = HcCall(ph);
  }
  err = HcStoreOCL(ph,0,server_id,err);
  return HcPostCall(ph,err);
}

