/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 24.11
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#include "HCPPHalcon_UI.h"

#ifndef __APPLE__
#  include "halconcpp/HalconAPI.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONCpp/HalconAPI.h>
#  else
#    include <HALCONCppxl/HalconAPI.h>
#  endif
#endif

extern "C" HUserImport int HHalcon_UIGetOffset();

int offset = -1;

using namespace HalconCpp;

Hproc_handle PreCallUser(int proc_index_local)
{
  if (offset < 0)
  {
    /* First use of this extension package, query my offset */
    if (0 > (offset = HHalcon_UIGetOffset()))
    {
      /*
       * Either the HALCON library was not initialized or the extension package
       * was not loaded. Make sure HALCON is initialized and check the offset
       * again.
       */
      Hproc_handle tmp = HalconAPI::PreCall(0);
      HalconAPI::PostCall(tmp);
      if (0 > (offset = HHalcon_UIGetOffset()))
      {
        /* The extension package could not be loaded. */
        HOperatorException::Throw(-1,H_ERR_UEXTNI);
      }
    }
  }
  return HalconAPI::PreCall(offset + proc_index_local);
}




#ifdef WCloseWebServer
# error An existing macro name conflicts with WCloseWebServer
#endif
HUserExport void HalconCpp::WCloseWebServer(const HTuple& server_id)
{
  Hproc_handle proc = PreCallUser(0);
  HalconAPI::Store(proc,0,server_id);
  HalconAPI::CallProcedure(proc);
  HalconAPI::PostCall(proc);
}

#ifdef WSendWebData
# error An existing macro name conflicts with WSendWebData
#endif
HUserExport void HalconCpp::WSendWebData(const HTuple& server_id, const HTuple& DictHandle)
{
  Hproc_handle proc = PreCallUser(1);
  HalconAPI::Store(proc,0,server_id);
  HalconAPI::Store(proc,1,DictHandle);
  HalconAPI::CallProcedure(proc);
  HalconAPI::PostCall(proc);
}

#ifdef WRecvWebData
# error An existing macro name conflicts with WRecvWebData
#endif
HUserExport void HalconCpp::WRecvWebData(const HTuple& server_id, const HTuple& timeout, const HTuple& DictHandle)
{
  Hproc_handle proc = PreCallUser(2);
  HalconAPI::Store(proc,0,server_id);
  HalconAPI::Store(proc,1,timeout);
  HalconAPI::Store(proc,2,DictHandle);
  HalconAPI::CallProcedure(proc);
  HalconAPI::PostCall(proc);
}

#ifdef WCreateWebServer
# error An existing macro name conflicts with WCreateWebServer
#endif
HUserExport void HalconCpp::WCreateWebServer(const HTuple& port, HTuple* server_id)
{
  Hproc_handle proc = PreCallUser(3);
  HalconAPI::Store(proc,0,port);
  HalconAPI::InitOutp(proc,0);
  HalconAPI::CallProcedure(proc);
  HalconAPI::Load(proc,0,server_id);
  HalconAPI::PostCall(proc);
}

