/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 24.11
 * Usage: Initialization of operator table
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef H_BUILD_WITH_HLIBXPI
#  ifndef __APPLE__
#    include "Halcon.h"
#    include "HCtype.h"
#  else
#    ifndef HC_LARGE_IMAGES
#      include <HALCON/Halcon.h>
#      include <HALCON/HCtype.h>
#    else
#      include <HALCONxl/Halcon.h>
#      include <HALCONxl/HCtype.h>
#    endif
#  endif
#else
#  include "HlibXpi.h"
#endif
Herror CCloseWebServer(Hproc_handle proc_id);
Herror CSendWebData(Hproc_handle proc_id);
Herror CRecvWebData(Hproc_handle proc_id);
Herror CCreateWebServer(Hproc_handle proc_id);



static Herror HSystem0(int32_t xid)
{
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_ParameterType,0,"h"));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumInpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumOutpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumInpCtrlPar,1));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_NumOutpCtrlPar,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_LogicalName,"WCloseWebServer"));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_PhysicalName,"CCloseWebServer"));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_procedure,CCloseWebServer));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_module,1ul));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_process_excl_local,HAG_PAR_NO_RESTRICT));
#ifndef HC_NO_COMPUTE_DEVICES
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_compute_device,0));
#endif
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_parallelization,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_aopCost,NULL));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_numCost,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_parallelMinCosts,0));
  HCkP(HXPkgSetOpInfo(xid,0,HOIID_parallelRegionsplit,0));

  HCkP(HXPkgSetOpInfo(xid,1,HOIID_ParameterType,0,"hh"));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_NumInpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_NumOutpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_NumInpCtrlPar,2));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_NumOutpCtrlPar,0));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_LogicalName,"WSendWebData"));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_PhysicalName,"CSendWebData"));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_procedure,CSendWebData));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_module,1ul));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_process_excl_local,HAG_PAR_NO_RESTRICT));
#ifndef HC_NO_COMPUTE_DEVICES
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_compute_device,0));
#endif
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_parallelization,0));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_aopCost,NULL));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_numCost,0));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_parallelMinCosts,0));
  HCkP(HXPkgSetOpInfo(xid,1,HOIID_parallelRegionsplit,0));

  HCkP(HXPkgSetOpInfo(xid,2,HOIID_ParameterType,0,"hih"));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_NumInpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_NumOutpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_NumInpCtrlPar,3));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_NumOutpCtrlPar,0));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_LogicalName,"WRecvWebData"));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_PhysicalName,"CRecvWebData"));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_procedure,CRecvWebData));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_module,1ul));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_process_excl_local,HAG_PAR_NO_RESTRICT));
#ifndef HC_NO_COMPUTE_DEVICES
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_compute_device,0));
#endif
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_parallelization,0));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_aopCost,NULL));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_numCost,0));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_parallelMinCosts,0));
  HCkP(HXPkgSetOpInfo(xid,2,HOIID_parallelRegionsplit,0));

  HCkP(HXPkgSetOpInfo(xid,3,HOIID_ParameterType,0,"is"));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_ParameterType,1,"h"));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_NumInpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_NumOutpObjPar,0));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_NumInpCtrlPar,2));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_NumOutpCtrlPar,1));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_LogicalName,"WCreateWebServer"));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_PhysicalName,"CCreateWebServer"));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_procedure,CCreateWebServer));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_module,1ul));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_process_excl_local,HAG_PAR_NO_RESTRICT));
#ifndef HC_NO_COMPUTE_DEVICES
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_compute_device,0));
#endif
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_parallelization,0));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_aopCost,NULL));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_numCost,0));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_parallelMinCosts,0));
  HCkP(HXPkgSetOpInfo(xid,3,HOIID_parallelRegionsplit,0));

return H_MSG_OK;
}
/******************************/



HINT m_offset = -1;

extern HUserExport int HHalcon_UIGetOffset()
{
  return m_offset;
}


HUserExport Herror HXPkgInit(int32_t xpkg_id)
{

  int32_t osid;
  HCkP(HXPkgOpenId(xpkg_id, HALCON_VERSION_CODE,H_OPERATOR_INFO_DERIVATE, 4, &osid));
  m_offset = osid;

  HCkP(HSystem0(xpkg_id));
  return H_MSG_OK;
}
