///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 24.11.1.0
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
///////////////////////////////////////////////////////////////////////////////
#include "HalconCpp.h"
#include "HDevThread.h"



using namespace HalconCpp;

// Procedure declarations 
// Local procedures 
void create_Control (HTuple hv_FatherHandle, HTuple hv_ID, HTuple hv_Type, HTuple hv_X, 
    HTuple hv_Y, HTuple hv_CX, HTuple hv_CY, HTuple hv_pName, HTuple hv_Text);

// Procedures 
// Local procedures 
void create_Control (HTuple hv_FatherHandle, HTuple hv_ID, HTuple hv_Type, HTuple hv_X, 
    HTuple hv_Y, HTuple hv_CX, HTuple hv_CY, HTuple hv_pName, HTuple hv_Text)
{

  // Local control variables
  HTuple  hv_Handle;

  CreateDict(&hv_Handle);
  if (0 != (HTuple(int(hv_ID<2)).TupleOr(int(hv_ID>65535))))
  {
    throw HException(//'ID要大于2，小于65535'
      "ID\350\246\201\345\244\247\344\272\2162\357\274\214\345\260\217\344\272\21665535");
  }
  SetDictTuple(hv_Handle, //'控件ID'
      "\346\216\247\344\273\266ID", hv_ID);
  SetDictTuple(hv_Handle, //'控件类型'
      "\346\216\247\344\273\266\347\261\273\345\236\213", 
      hv_Type);
  SetDictTuple(hv_Handle, "X", hv_X);
  SetDictTuple(hv_Handle, "Y", hv_Y);
  SetDictTuple(hv_Handle, "CX", hv_CX);
  SetDictTuple(hv_Handle, "CY", hv_CY);
  SetDictTuple(hv_Handle, //'标题'
      "\346\240\207\351\242\230", hv_pName);
  SetDictTuple(hv_Handle, //'默认内容'
      "\351\273\230\350\256\244\345\206\205\345\256\271", 
      hv_Text);

  SetDictTuple(hv_FatherHandle, //'控件'
      "\346\216\247\344\273\266"+hv_ID, 
      hv_Handle);
  return;
}

#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{

  // Local control variables
  HTuple  hv_RootHandle, hv_GenParamValue, hv_Index;
  HTuple  hv_ControlHandle, hv_ControlType, hv_ID, hv_X, hv_Y;
  HTuple  hv_CX, hv_CY, hv_pName, hv_Text;

  CreateDict(&hv_RootHandle);
  create_Control(hv_RootHandle, 2, //'按钮'
      "\346\214\211\351\222\256", 200, 
      10, 100, 20, //'按钮'
      "\346\214\211\351\222\256", "");
  create_Control(hv_RootHandle, 3, //'参数'
      "\345\217\202\346\225\260", 200, 
      210, 100, 20, //'按钮'
      "\346\214\211\351\222\256", "55");
  create_Control(hv_RootHandle, 4, //'树型'
      "\346\240\221\345\236\213", 200, 
      410, 100, 20, //'按钮'
      "\346\214\211\351\222\256", "");
  create_Control(hv_RootHandle, 5, //'文件'
      "\346\226\207\344\273\266", 200, 
      610, 100, 20, //'按钮'
      "\346\214\211\351\222\256", "");
  create_Control(hv_RootHandle, 6, //'文件夹'
      "\346\226\207\344\273\266\345\244\271", 
      200, 810, 100, 20, //'按钮'
      "\346\214\211\351\222\256", "");
  create_Control(hv_RootHandle, 7, //'图片'
      "\345\233\276\347\211\207", 500, 
      200, 300, 300, //'按钮'
      "\346\214\211\351\222\256", "");
  GetDictParam(hv_RootHandle, "keys", HTuple(), &hv_GenParamValue);
  {
  HTuple end_val8 = hv_GenParamValue.TupleLength();
  HTuple step_val8 = 1;
  for (hv_Index=0; hv_Index.Continue(end_val8, step_val8); hv_Index += step_val8)
  {
    GetDictTuple(hv_RootHandle, HTuple(hv_GenParamValue[hv_Index]), &hv_ControlHandle);
    GetDictTuple(hv_ControlHandle, //'控件类型'
      "\346\216\247\344\273\266\347\261\273\345\236\213", 
        &hv_ControlType);
    if (0 != (int(hv_ControlType==//'按钮'
      HTuple("\346\214\211\351\222\256"))))
    {
      GetDictTuple(hv_ControlHandle, //'控件ID'
      "\346\216\247\344\273\266ID", 
          &hv_ID);
      GetDictTuple(hv_ControlHandle, "X", &hv_X);
      GetDictTuple(hv_ControlHandle, "Y", &hv_Y);
      GetDictTuple(hv_ControlHandle, "CX", &hv_CX);
      GetDictTuple(hv_ControlHandle, "CY", &hv_CY);
      GetDictTuple(hv_ControlHandle, //'标题'
      "\346\240\207\351\242\230", 
          &hv_pName);

    }
    else if (0 != (int(hv_ControlType==//'参数'
      HTuple("\345\217\202\346\225\260"))))
    {
      GetDictTuple(hv_ControlHandle, //'控件ID'
      "\346\216\247\344\273\266ID", 
          &hv_ID);
      GetDictTuple(hv_ControlHandle, "X", &hv_X);
      GetDictTuple(hv_ControlHandle, "Y", &hv_Y);
      GetDictTuple(hv_ControlHandle, "CX", &hv_CX);
      GetDictTuple(hv_ControlHandle, "CY", &hv_CY);
      GetDictTuple(hv_ControlHandle, //'标题'
      "\346\240\207\351\242\230", 
          &hv_pName);
      GetDictTuple(hv_ControlHandle, //'默认内容'
      "\351\273\230\350\256\244\345\206\205\345\256\271", 
          &hv_Text);

    }
    else if (0 != (int(hv_ControlType==//'树型'
      HTuple("\346\240\221\345\236\213"))))
    {
      GetDictTuple(hv_ControlHandle, //'控件ID'
      "\346\216\247\344\273\266ID", 
          &hv_ID);
      GetDictTuple(hv_ControlHandle, "X", &hv_X);
      GetDictTuple(hv_ControlHandle, "Y", &hv_Y);
      GetDictTuple(hv_ControlHandle, "CX", &hv_CX);
      GetDictTuple(hv_ControlHandle, "CY", &hv_CY);
      GetDictTuple(hv_ControlHandle, //'标题'
      "\346\240\207\351\242\230", 
          &hv_pName);
    }
    else if (0 != (int(hv_ControlType==//'文件'
      HTuple("\346\226\207\344\273\266"))))
    {
      GetDictTuple(hv_ControlHandle, //'控件ID'
      "\346\216\247\344\273\266ID", 
          &hv_ID);
      GetDictTuple(hv_ControlHandle, "X", &hv_X);
      GetDictTuple(hv_ControlHandle, "Y", &hv_Y);
      GetDictTuple(hv_ControlHandle, "CX", &hv_CX);
      GetDictTuple(hv_ControlHandle, "CY", &hv_CY);
      GetDictTuple(hv_ControlHandle, //'标题'
      "\346\240\207\351\242\230", 
          &hv_pName);
      GetDictTuple(hv_ControlHandle, //'默认内容'
      "\351\273\230\350\256\244\345\206\205\345\256\271", 
          &hv_Text);
    }
    else if (0 != (int(hv_ControlType==//'文件夹'
      HTuple("\346\226\207\344\273\266\345\244\271"))))
    {
      GetDictTuple(hv_ControlHandle, //'控件ID'
      "\346\216\247\344\273\266ID", 
          &hv_ID);
      GetDictTuple(hv_ControlHandle, "X", &hv_X);
      GetDictTuple(hv_ControlHandle, "Y", &hv_Y);
      GetDictTuple(hv_ControlHandle, "CX", &hv_CX);
      GetDictTuple(hv_ControlHandle, "CY", &hv_CY);
      GetDictTuple(hv_ControlHandle, //'标题'
      "\346\240\207\351\242\230", 
          &hv_pName);
      GetDictTuple(hv_ControlHandle, //'默认内容'
      "\351\273\230\350\256\244\345\206\205\345\256\271", 
          &hv_Text);
    }
    else if (0 != (int(hv_ControlType==//'图片'
      HTuple("\345\233\276\347\211\207"))))
    {
      GetDictTuple(hv_ControlHandle, //'控件ID'
      "\346\216\247\344\273\266ID", 
          &hv_ID);
      GetDictTuple(hv_ControlHandle, "X", &hv_X);
      GetDictTuple(hv_ControlHandle, "Y", &hv_Y);
      GetDictTuple(hv_ControlHandle, "CX", &hv_CX);
      GetDictTuple(hv_ControlHandle, "CY", &hv_CY);
      GetDictTuple(hv_ControlHandle, //'标题'
      "\346\240\207\351\242\230", 
          &hv_pName);
    }
    else if (0 != (int(hv_ControlType==//'文本'
      HTuple("\346\226\207\346\234\254"))))
    {
      GetDictTuple(hv_ControlHandle, //'控件ID'
      "\346\216\247\344\273\266ID", 
          &hv_ID);
      GetDictTuple(hv_ControlHandle, "X", &hv_X);
      GetDictTuple(hv_ControlHandle, "Y", &hv_Y);
      GetDictTuple(hv_ControlHandle, "CX", &hv_CX);
      GetDictTuple(hv_ControlHandle, "CY", &hv_CY);
      GetDictTuple(hv_ControlHandle, //'标题'
      "\346\240\207\351\242\230", 
          &hv_pName);
    }



  }
  }



}


#ifndef NO_EXPORT_APP_MAIN


int main(int argc, char *argv[])
{
  int ret = 0;

  try
  {
#if defined(_WIN32)
    SetSystem("use_window_thread", "true");
#endif

    // Default settings used in HDevelop (can be omitted)
    SetSystem("width", 512);
    SetSystem("height", 512);

    action();
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            exception.ProcName().TextA(),
            exception.ErrorMessage().TextA());
    ret = 1;
  }

#if defined(_WIN32)
  // On Windows socket communication is no longer possible after returning
  // from main, so HALCON cannot return floating licenses automatically.
  try
  {
    SetSystem("return_license", "true");
  }
  catch (...)
  {
    // Ignore any errors that might occur when returning the license.
  }
#endif

  return ret;
}

#endif


#endif


